spring:
  application:
    name: friendly-fortnight-backend
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
#    instance-id: ${spring.application.name}:${random.value}

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1320000
ribbon:
  eager-load:
    enabled: true